package com.mcp.tools.tool;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.annotation.PostConstruct;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.UUID;

/**
 * HTML 生成器 — 纯 Java 生成 HTML 文档，无需额外依赖。
 *
 * 输入格式（LLM JSON）：
 * {
 *   "title": "页面标题",
 *   "sections": [
 *     {"title": "第一节", "content": ["段落1", "段落2"]},
 *     {"title": "第二节", "content": ["..."]}
 *   ]
 * }
 */
@Slf4j
@Component
public class HtmlGeneratorTool implements DocumentGenerator {

    private final ObjectMapper objectMapper = new ObjectMapper();

    @Value("${html.output.dir:./generated/html}")
    private String outputDir;

    private static final DateTimeFormatter TS_FMT = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");

    private static final String CSS_STYLE = """
            <style>
                body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 40px auto;
                       padding: 20px; color: #333; line-height: 1.6; }
                h1 { color: #1a1a2e; border-bottom: 3px solid #4a90d9; padding-bottom: 10px; }
                h2 { color: #2c3e50; margin-top: 30px; border-left: 4px solid #4a90d9; padding-left: 12px; }
                p { margin: 8px 0; }
                ul { padding-left: 24px; }
                li { margin: 4px 0; }
                code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }
                pre { background: #2d2d2d; color: #f8f8f2; padding: 16px; border-radius: 6px;
                      overflow-x: auto; }
                table { border-collapse: collapse; width: 100%; margin: 16px 0; }
                th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
                th { background: #4a90d9; color: white; }
                tr:nth-child(even) { background: #f9f9f9; }
                .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #eee;
                          font-size: 0.85em; color: #999; }
            </style>
            """;

    @PostConstruct
    public void init() {
        log.info("[HtmlGen] Output directory: {}", outputDir);
    }

    @Override
    public DocResult generate(String llmResponse, String userTitle) throws Exception {
        Path dir = Path.of(outputDir).toAbsolutePath().normalize();
        Files.createDirectories(dir);

        JsonNode root;
        try {
            root = objectMapper.readTree(llmResponse);
        } catch (Exception e) {
            root = null;
        }
        String title = root != null && root.has("title") ? root.get("title").asText() : userTitle;
        JsonNode sections = root != null && root.has("sections") ? root.get("sections") : null;

        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>\n<html lang=\"zh-CN\">\n<head>\n");
        html.append("<meta charset=\"UTF-8\">\n");
        html.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("<title>").append(escapeHtml(title)).append("</title>\n");
        html.append(CSS_STYLE);
        html.append("</head>\n<body>\n");
        html.append("<h1>").append(escapeHtml(title)).append("</h1>\n");

        if (sections != null && sections.isArray()) {
            for (JsonNode section : sections) {
                if (section.has("title")) {
                    html.append("<h2>").append(escapeHtml(section.get("title").asText())).append("</h2>\n");
                }
                JsonNode contentItems = section.get("content");
                if (contentItems != null && contentItems.isArray()) {
                    for (JsonNode item : contentItems) {
                        html.append("<p>").append(escapeHtml(item.asText())).append("</p>\n");
                    }
                }
            }
        } else {
            String[] paragraphs = llmResponse.split("\n\n");
            for (String para : paragraphs) {
                String trimmed = para.trim();
                if (trimmed.isEmpty()) continue;
                if (trimmed.startsWith("```")) {
                    html.append("<pre>").append(escapeHtml(trimmed)).append("</pre>\n");
                } else {
                    html.append("<p>").append(escapeHtml(trimmed)).append("</p>\n");
                }
            }
        }

        html.append("<div class=\"footer\">\n");
        html.append("<p>Generated by MCP Agent Orchestrator at ")
                .append(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")))
                .append("</p>\n</div>\n");
        html.append("</body>\n</html>");

        String fileName = sanitizeFileName(title) + "_" + TS_FMT.format(LocalDateTime.now()) + ".html";
        Path filePath = dir.resolve(fileName);
        Files.writeString(filePath, html.toString(), StandardCharsets.UTF_8);

        long size = Files.size(filePath);
        log.info("[HtmlGen] Generated: {} ({} bytes)", fileName, size);
        return new DocResult(fileName, "/files/html/" + fileName,
                "text/html; charset=utf-8", size, "HTML 生成成功: " + fileName);
    }

    @Override
    public DocResult generateFromMarkdown(String markdownContent, String title) throws Exception {
        String json = "{\"title\":\"" + escapeJson(title) + "\",\"sections\":[{\"content\":[\"" +
                escapeJson(markdownContent) + "\"]}]}";
        return generate(json, title);
    }

    @Override
    public boolean supports(String format) {
        return "html".equalsIgnoreCase(format);
    }

    private String escapeHtml(String text) {
        if (text == null) return "";
        return text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }

    private String sanitizeFileName(String name) {
        if (name == null || name.isBlank()) return "document";
        return name.replaceAll("[\\\\/:*?\"<>|]", "_").substring(0, Math.min(name.length(), 50));
    }

    private String escapeJson(String text) {
        return text.replace("\\", "\\\\").replace("\"", "\\\"")
                .replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t");
    }
}