<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.origamihe</groupId>
        <artifactId>mcp-agent-orchestrator</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>mcp-llm</artifactId>
    <packaging>jar</packaging>

    <name>mcp-llm</name>
    <description>LLM 客户端集成层（支持多模型提供商）</description>

    <dependencies>
        <dependency>
            <groupId>io.github.origamihe</groupId>
            <artifactId>mcp-common</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.origamihe</groupId>
            <artifactId>mcp-core</artifactId>
        </dependency>

        <!--引用deepSeek-->
        <!-- <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-starter-model-deepseek</artifactId>
            </dependency>-->

        <!-- 引用openai -->
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-starter-model-openai</artifactId>
        </dependency>

    </dependencies>

    <!-- 如果 Maven 依然报找不到（Could not find...），需要添加 Spring 官方的里程碑仓库 -->
    <repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
</project>
