<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.origamihe</groupId>
        <artifactId>mcp-agent-orchestrator</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>mcp-starter</artifactId>
    <packaging>jar</packaging>

    <name>mcp-starter</name>
    <description>模块描述...</description>

    <dependencies>

        <dependency>
            <groupId>io.github.origamihe</groupId>
            <artifactId>mcp-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>   <!-- 推荐使用 WebFlux，更适合 MCP 异步协议 -->
        </dependency>

        <dependency>
            <groupId>io.github.origamihe</groupId>
            <artifactId>mcp-gateway</artifactId>
        </dependency>
    </dependencies>
</project>